# Generated by Django 5.0.4 on 2024-05-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressure', models.FloatField()),
                ('particulate_matter1', models.FloatField()),
                ('particulate_matter2', models.FloatField()),
                ('particulate_matter3', models.FloatField()),
                ('atmospheric_moisture', models.FloatField()),
                ('luminosity', models.FloatField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('classification', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Soilmoisture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(max_length=100)),
                ('humidity', models.CharField(max_length=100)),
                ('moisture', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'soilmoisture',
            },
        ),
    ]
